### ISSUE TITLE
type  和 __class__的区别是什么呢

### ISSUE THREAD

**Issue by chargerKong** [Ltuzhi/Python#1]
num1=123
print(type(num1))

print((num1.__class__))

**Comment by Ltuzhi** [comment]
type是一个函数来来获取类的类型，而__class__是类的属性的方式来获取类的类型，不同方法获取相同的东西。

**Comment by chargerKong** [comment]
> type是一个函数来来获取类的类型，而__class__是类的属性的方式来获取类的类型，不同方法获取相同的东西。

哇~ 小宝贝你可真聪明
